=begin
#LocationIQ

#LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for LocationIQClient::BalanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BalanceApi' do
  before do
    # run before each test
    @instance = LocationIQClient::BalanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BalanceApi' do
    it 'should create an instance of BalanceApi' do
      expect(@instance).to be_instance_of(LocationIQClient::BalanceApi)
    end
  end

  # unit tests for balance
  # The Balance API provides a count of request credits left in the user&#39;s account for the day. Balance is reset at midnight UTC everyday (00:00 UTC).
  # @param [Hash] opts the optional parameters
  # @return [Balance]
  describe 'balance test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
