=begin
#LocationIQ

#LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.

The version of the OpenAPI document: 1.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/address'
require 'openapi_client/models/balance'
require 'openapi_client/models/daybalance'
require 'openapi_client/models/directions_directions'
require 'openapi_client/models/directions_directions_routes'
require 'openapi_client/models/directions_matching'
require 'openapi_client/models/directions_matrix'
require 'openapi_client/models/directions_matrix_sources'
require 'openapi_client/models/directions_nearest'
require 'openapi_client/models/directions_nearest_waypoints'
require 'openapi_client/models/error'
require 'openapi_client/models/location'
require 'openapi_client/models/matchquality'
require 'openapi_client/models/namedetails'

# APIs
require 'openapi_client/api/autocomplete_api'
require 'openapi_client/api/balance_api'
require 'openapi_client/api/directions_api'
require 'openapi_client/api/matching_api'
require 'openapi_client/api/matrix_api'
require 'openapi_client/api/nearest_api'
require 'openapi_client/api/reverse_api'
require 'openapi_client/api/search_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
