=begin
#LocationIQ

#LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.

The version of the OpenAPI document: 1.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'cgi'

module LocationIQClient
  class MatchingApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Matching Service
    # Matching API matches or snaps given GPS points to the road network in the most plausible way.  Please note the request might result multiple sub-traces.  Large jumps in the timestamps (> 60s) or improbable transitions lead to trace splits if a complete matching could not be found. The algorithm might not be able to match all points. Outliers are removed if they can not be matched successfully.
    # @param coordinates [String] String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google&#39;s polyline format with precision 5
    # @param [Hash] opts the optional parameters
    # @option opts [String] :generate_hints Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String
    # @option opts [String] :approaches Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default)
    # @option opts [String] :exclude Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none.
    # @option opts [String] :bearings Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180
    # @option opts [String] :radiuses Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double &gt;&#x3D; 0 or unlimited (default)
    # @option opts [String] :steps Returned route steps for each route leg [ true, false (default) ]
    # @option opts [String] :annotations Returns additional metadata for each coordinate along the route geometry.  [ true, false (default), nodes, distance, duration, datasources, weight, speed ] (default to '\"false\"')
    # @option opts [String] :geometries Returned route geometry format (influences overview and per step) [ polyline (default), polyline6, geojson ] (default to '\"polyline\"')
    # @option opts [String] :overview Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all. [ simplified (default), full, false ] (default to '\"simplified\"')
    # @option opts [String] :timestamps Timestamps for the input locations in seconds since UNIX epoch. Timestamps need to be monotonically increasing. [ {timestamp};{timestamp}[;{timestamp} ...]  integer seconds since UNIX epoch
    # @option opts [String] :gaps Allows the input track splitting based on huge timestamp gaps between points. [ split (default), ignore ] (default to '\"split\"')
    # @option opts [String] :tidy Allows the input track modification to obtain better matching quality for noisy tracks. [ true, false (default) ] (default to '\"false\"')
    # @option opts [String] :waypoints Treats input coordinates indicated by given indices as waypoints in returned Match object. Default is to treat all input coordinates as waypoints. [ {index};{index};{index}... ]
    # @return [DirectionsMatching]
    def matching(coordinates, opts = {})
      data, _status_code, _headers = matching_with_http_info(coordinates, opts)
      data
    end

    # Matching Service
    # Matching API matches or snaps given GPS points to the road network in the most plausible way.  Please note the request might result multiple sub-traces.  Large jumps in the timestamps (&gt; 60s) or improbable transitions lead to trace splits if a complete matching could not be found. The algorithm might not be able to match all points. Outliers are removed if they can not be matched successfully.
    # @param coordinates [String] String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google&#39;s polyline format with precision 5
    # @param [Hash] opts the optional parameters
    # @option opts [String] :generate_hints Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String
    # @option opts [String] :approaches Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default)
    # @option opts [String] :exclude Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none.
    # @option opts [String] :bearings Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180
    # @option opts [String] :radiuses Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double &gt;&#x3D; 0 or unlimited (default)
    # @option opts [String] :steps Returned route steps for each route leg [ true, false (default) ]
    # @option opts [String] :annotations Returns additional metadata for each coordinate along the route geometry.  [ true, false (default), nodes, distance, duration, datasources, weight, speed ]
    # @option opts [String] :geometries Returned route geometry format (influences overview and per step) [ polyline (default), polyline6, geojson ]
    # @option opts [String] :overview Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all. [ simplified (default), full, false ]
    # @option opts [String] :timestamps Timestamps for the input locations in seconds since UNIX epoch. Timestamps need to be monotonically increasing. [ {timestamp};{timestamp}[;{timestamp} ...]  integer seconds since UNIX epoch
    # @option opts [String] :gaps Allows the input track splitting based on huge timestamp gaps between points. [ split (default), ignore ]
    # @option opts [String] :tidy Allows the input track modification to obtain better matching quality for noisy tracks. [ true, false (default) ]
    # @option opts [String] :waypoints Treats input coordinates indicated by given indices as waypoints in returned Match object. Default is to treat all input coordinates as waypoints. [ {index};{index};{index}... ]
    # @return [Array<(DirectionsMatching, Integer, Hash)>] DirectionsMatching data, response status code and response headers
    def matching_with_http_info(coordinates, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MatchingApi.matching ...'
      end
      # verify the required parameter 'coordinates' is set
      if @api_client.config.client_side_validation && coordinates.nil?
        fail ArgumentError, "Missing the required parameter 'coordinates' when calling MatchingApi.matching"
      end
      # resource path
      local_var_path = '/matching/driving/{coordinates}'.sub('{' + 'coordinates' + '}', CGI.escape(coordinates.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'generate_hints'] = opts[:'generate_hints'] if !opts[:'generate_hints'].nil?
      query_params[:'approaches'] = opts[:'approaches'] if !opts[:'approaches'].nil?
      query_params[:'exclude'] = opts[:'exclude'] if !opts[:'exclude'].nil?
      query_params[:'bearings'] = opts[:'bearings'] if !opts[:'bearings'].nil?
      query_params[:'radiuses'] = opts[:'radiuses'] if !opts[:'radiuses'].nil?
      query_params[:'steps'] = opts[:'steps'] if !opts[:'steps'].nil?
      query_params[:'annotations'] = opts[:'annotations'] if !opts[:'annotations'].nil?
      query_params[:'geometries'] = opts[:'geometries'] if !opts[:'geometries'].nil?
      query_params[:'overview'] = opts[:'overview'] if !opts[:'overview'].nil?
      query_params[:'timestamps'] = opts[:'timestamps'] if !opts[:'timestamps'].nil?
      query_params[:'gaps'] = opts[:'gaps'] if !opts[:'gaps'].nil?
      query_params[:'tidy'] = opts[:'tidy'] if !opts[:'tidy'].nil?
      query_params[:'waypoints'] = opts[:'waypoints'] if !opts[:'waypoints'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:body] 

      # return_type
      return_type = opts[:return_type] || 'DirectionsMatching' 

      # auth_names
      auth_names = opts[:auth_names] || ['key']

      new_options = opts.merge(
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MatchingApi#matching\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
