=begin
#LocationIQ

#LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.

OpenAPI spec version: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.2.3

=end

module LocationIQClient
  VERSION = '1.0.1'
end
